Disable build check in pre-commit hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,7 +1,7 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-echo "Starting pre-commit style, test, and build checks..."
+echo "Starting pre-commit style, lint, and type checks..."
 
 # Check Prettier standards
 npm run check-format || (
@@ -24,11 +24,11 @@ npm run check-types || (
   false;
 )
 
-# Check build
-npm run build || (
-  echo "Build failed."
-  echo "Fix the issues above and try again."
-  false;
-)
+# # Check build
+# npm run build || (
+#   echo "Build failed."
+#   echo "Fix the issues above and try again."
+#   false;
+# )
 
 echo "All checks passed."
